name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install build deps
      run: |
        sudo apt update
        sudo apt install -y libsdl3-dev libsdl3-0 g++ g++-mingw-w64

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: Build
      run: |
        bash build.sh
        bash build_windows.sh
        cp sdl3_prebuilt/SDL3.dll ./

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: sdl_joystick_dumper_${{ env.sha_name }}
        path: |
           sdl_joystick_dumper
           sdl_joystick_dumper.exe
           SDL3.dll
        if-no-files-found: error
